backend:
  name: github
  repo: jecatalan-aa/aulaactiva-web # Asegúrate que esto sea TU_USUARIO/TU_REPOSITORIO
  branch: main
  site_id: 7d30f4a3-e4d7-4433-bc34-cc18234bcf13
 

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de Publicación", name: "date", widget: "datetime"}
      - {label: "Imagen Principal", name: "thumbnail", widget: "image"}
      - {label: "Autor", name: "author", widget: "string", default: "AulaActiva"}
      - {label: "Cuerpo del Post", name: "body", widget: "markdown"}